// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssbahthocmahojnduazb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzYmFodGhvY21haG9qbmR1YXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Mjc0NTQsImV4cCI6MjA3NDUwMzQ1NH0.ucIIjNw3Y3RDMq0UfD-g4sz6srO2Ml7mbVL37pc3t8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});